version: '3'
services:

  mongodb:
    image: mongo:3.2
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: shorturl
      MONGO_INITDB_ROOT_PASSWORD: 123123
      MONGO_INITDB_DATABASE: shorturl
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./shorturl:/data/db
    networks:
      - mongo-shorturl
    ports:
      - "27017:27017"
      
  frontend:
    image: "node:lts-alpine"
    container_name: vue-node-shorturl
    working_dir: ./shorturl/frontend
    restart: always
    volumes:
      - ./frontend:./shorturl/frontend
    ports:
      - "4000:8080"
    expose:
      - "8080"
    networks:
      - default
    command: >
      sh -c "npm install 
             npm run serve"
    depends_on:
      - mongodb
  
networks:
  mongo-shorturl:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 10.0.238.0/24